### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by tawhidii** [john-smilga/strapi-gatsby-porfolio-2020-api#9]
I cloned your repo and try to run and I got error given below. Can you tell me why this is happening?? 
```
barii@n00b:~/Desktop/MYLINUX/other-api$ npm run develop

> portfolio-api@0.1.0 develop /home/barii/Desktop/MYLINUX/other-api
> strapi develop

[2020-11-06T15:57:10.749Z] debug ⛔️ Server wasn't able to start properly.
[2020-11-06T15:57:10.750Z] error TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Object.load (/home/barii/Desktop/MYLINUX/other-api/node_modules/strapi-database/lib/connector-registry.js:17:39)
    at DatabaseManager.initialize (/home/barii/Desktop/MYLINUX/other-api/node_modules/strapi-database/lib/database-manager.js:32:21)
    at Strapi.load (/home/barii/Desktop/MYLINUX/other-api/node_modules/strapi/lib/Strapi.js:311:19)
    at async Strapi.start (/home/barii/Desktop/MYLINUX/other-api/node_modules/strapi/lib/Strapi.js:190:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! portfolio-api@0.1.0 develop: `strapi develop`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the portfolio-api@0.1.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/barii/.npm/_logs/2020-11-06T15_57_10_771Z-debug.log
```

**Comment by tawhidii** [comment]
no response .. closed the issues :)
